### Listar alquileres
GET http://localhost:5000/alquileres
Content-Type: application/json



### Crear alquiler
# "costo_total" se calcula automaticamente.
# "id_reserva" es opcional, se usa si el alquiler proviene de una reserva confirmada.
POST http://localhost:5000/alquileres
Content-Type: application/json

{
    "id_cliente": 1,
    "id_empleado": 1,
    "id_vehiculo": 2,
    "id_reserva": 2
}


### Obtener alquiler por ID
GET http://localhost:5000/alquileres/1
Content-Type: application/json


### Obtener alquiler por estado o estados
GET http://localhost:5000/alquileres/estado/ACTIVO
Content-Type: application/json


### Obtener alquileres por período
GET http://localhost:5000/alquileres/periodo?desde=2024-01-01&hasta=2026-03-01
Content-Type: application/json


### Actualizar alquiler
PUT http://localhost:5000/alquileres/1
Content-Type: application/json

{
    "id_cliente": 1,
    "id_empleado": 1,
    "id_vehiculo": 2,
    "fecha_inicio": "2026-01-12",
    "fecha_fin": "2026-01-18",
}


### Listar alquileres por cliente
GET http://localhost:5000/alquileres/cliente/1
Content-Type: application/json


### Listar alquileres por vehículo
GET http://localhost:5000/alquileres/vehiculo/2
Content-Type: application/json


### Finalizar alquiler
PATCH http://localhost:5000/alquileres/2/finalizar
Content-Type: application/json
