@baseUrl = http://localhost:5000


### Login empleado
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "password": "admin123"
}


### Listar alquileres
GET {{baseUrl}}/alquileres
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Crear alquiler
# "costo_total" se calcula automaticamente.
# "id_reserva" es opcional, se usa si el alquiler proviene de una reserva confirmada.
POST {{baseUrl}}/alquileres
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_cliente": 1,
    "id_empleado": 2,
    "id_vehiculo": 1
}


### Obtener alquiler por ID
GET {{baseUrl}}/alquileres/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener alquiler por estado o estados
GET {{baseUrl}}/alquileres/estado/ACTIVO
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener alquileres por período
GET {{baseUrl}}/alquileres/periodo?desde=2024-01-01&hasta=2026-03-01
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener vehículos más alquilados (por defecto 5)
GET  {{baseUrl}}/alquileres/vehiculos-mas-alquilados
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener vehículos más alquilados (cantidad personalizada)
GET {{baseUrl}}/alquileres/vehiculos-mas-alquilados?limit=10
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener vehiculos mas alquilados en un período específico y con cantidad personalizada
GET {{baseUrl}}/alquileres/vehiculos-mas-alquilados?desde=2025-01-01&hasta=2025-12-31&limit=3
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Actualizar alquiler
PUT {{baseUrl}}/alquileres/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_cliente": 1,
    "id_empleado": 1,
    "id_vehiculo": 2,
    "fecha_inicio": "2026-01-12",
    "fecha_fin": "2026-01-18"
}


### Listar alquileres por cliente
GET {{baseUrl}}/alquileres/cliente/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Listar alquileres por vehículo
GET {{baseUrl}}/alquileres/vehiculo/2
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Finalizar alquiler
PATCH {{baseUrl}}/alquileres/1/finalizar
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}
