@baseUrl = http://127.0.0.1:5000


### Login empleado
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "password": "admin123"
}


### Obtener datos del empleado logueado
GET {{baseUrl}}/auth/me
Authorization: Bearer {{login.response.body.access_token}}


### Listar empleados (requiere token)
GET {{baseUrl}}/empleados
Authorization: Bearer {{login.response.body.access_token}}

