@baseUrl = http://127.0.0.1:5000


### Login empleado
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "password": "admin123"
}


### Listar clientes
GET {{baseUrl}}/clientes
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Crear cliente
POST {{baseUrl}}/clientes
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "nombre": "Francisco",
    "apellido": "Andrade",
    "dni": 11121111,
    "email": "fran.eze.andrade@gmail.com",
    "telefono": "3884216529",
    "licencia_numero": "ABC123",
    "licencia_categoria": "B1",
    "licencia_vencimiento": "2026-05-01"
}


### Obtener cliente por ID
GET {{baseUrl}}/clientes/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener cliente por DNI
GET {{baseUrl}}/clientes/dni/11111111
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener cliente por email
GET {{baseUrl}}/clientes/email/fran.eze.andrade@gmail.com
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Actualizar cliente
PUT {{baseUrl}}/clientes/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "nombre": "Francisco",
    "apellido": "Andrade",
    "dni": 11211111,
    "email": "otro.mail@gmail.com",
    "telefono": "388416529",
    "licencia_numero": "ABC123",
    "licencia_categoria": "B1",
    "licencia_vencimiento": "2026-05-01"
}


### Eliminar cliente
DELETE {{baseUrl}}/clientes/3
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}