@baseUrl = http://127.0.0.1:5000

### Login empleado
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "password": "admin123"
}

### Listar marcas
GET {{baseUrl}}/marcas
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

### Crear marca
POST {{baseUrl}}/marcas
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "nombre": "BM"
}


### Obtener marca por ID
GET {{baseUrl}}/marcas/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener marca por nombre
GET {{baseUrl}}/marcas/nombre/BMW
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Actualizar marca
PUT {{baseUrl}}/marcas/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "nombre": "BMW"
}


### Eliminar marca
DELETE {{baseUrl}}/marcas/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}