@baseUrl = http://127.0.0.1:5000

### Login empleado
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "password": "admin123"
}


### Listar modelos
GET {{baseUrl}}/modelos
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Crear modelo
POST {{baseUrl}}/modelos
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_marca": 1,
    "nombre": "Serie 2",
    "descripcion": "Deportivo compacto"
}


### Obtener modelo por ID
GET {{baseUrl}}/modelos/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Actualizar modelo
PUT {{baseUrl}}/modelos/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}
{
    "id_marca": 1,
    "nombre": "Serie 4",
    "descripcion": "Deportivo compacto"
}


### Eliminar modelo
DELETE {{baseUrl}}/modelos/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}