### Listar multas
GET http://localhost:5000/multas
Content-Type: application/json


### Crear multa
POST http://localhost:5000/multas
Content-Type: application/json

{
    "id_alquiler": 1,
    "monto": 150.75,
    "fecha": "2024-06-15",
    "descripcion": "Exceso de velocidad"
}


### Obtener multa por ID
GET http://localhost:5000/multas/1
Content-Type: application/json


### Actualizar multa
PUT http://localhost:5000/multas/1
Content-Type: application/json

{
    "id_alquiler": 1,
    "monto": 200.00,
    "fecha": "2024-06-16",
    "descripcion": "Estacionamiento indebido"
}


### Eliminar multa
DELETE http://localhost:5000/multas/1
Content-Type: application/json
