@baseUrl = http://127.0.0.1:5000


### Login empleado
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "password": "admin123"
}


### Listar multas
GET {{baseUrl}}/multas
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Crear multa
POST {{baseUrl}}/multas
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_alquiler": 3,
    "monto": 150.75,
    "fecha": "2025-11-23",
    "descripcion": "Exceso de velocidad"
}


### Obtener multa por ID
GET {{baseUrl}}/multas/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Crear multa
POST {{baseUrl}}/multas
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_alquiler": 4,
    "monto": 100.00,
    "fecha": "2025-11-23",
    "descripcion": "Estacionamiento indebido"
}


### Actualizar multa
PUT {{baseUrl}}/multas/4
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_alquiler": 4,
    "monto": 200.00,
    "fecha": "2025-11-23",
    "descripcion": "Estacionamiento indebido"
}


### Eliminar multa
DELETE {{baseUrl}}/multas/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}