@baseUrl = http://127.0.0.1:5000

### Login empleado
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "password": "admin123"
}


### Listar reservas
GET {{baseUrl}}/reservas
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Crear reserva
POST {{baseUrl}}/reservas
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_cliente": 1,
    "id_vehiculo": 2,
    "fecha_inicio": "2026-11-22",
    "fecha_fin": "2026-11-25"
}


### Obtener reserva por ID

GET {{baseUrl}}/reservas/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Actualizar reserva
# Se usa para cambiar fechas / vehículo / cliente mientras la reserva esté en un estado válido.
PUT {{baseUrl}}/reservas/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_cliente": 1,
    "id_vehiculo": 1,
    "fecha_inicio": "2026-01-12",
    "fecha_fin": "2026-01-18",
}


### Obtener reservas por estado (uno o varios, separados por coma)
GET {{baseUrl}}/reservas/estado/CANCELADA
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Otro ejemplo con múltiples estados
GET {{baseUrl}}/reservas/estado/CANCELADA,CONFIRMADA
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener reservas por cliente  
GET {{baseUrl}}/reservas/cliente/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

### Cancelar reserva
PATCH {{baseUrl}}/reservas/1/cancelar
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}
