@baseUrl = http://127.0.0.1:5000


### Login empleado
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "password": "admin123"
}


### Listar vehículos
GET {{baseUrl}}/vehiculos
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Crear vehículo
POST {{baseUrl}}/vehiculos
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_modelo": 1,
"anio": 2022,
    "tipo": "SEDAN",
    "patente": "ABC12345",
    "costo_diario": 15000
}


### Obtener vehículo por ID
GET {{baseUrl}}/vehiculos/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Obtener vehículos por estado o estados
GET {{baseUrl}}/vehiculos/estado/DISPONIBLE
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### Actualizar vehículo
PUT {{baseUrl}}/vehiculos/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "id_modelo": 1,
    "anio": 2023,
    "tipo": "SEDAN",
    "patente": "ABC123",
    "costo_diario": 18000
}


### Eliminar vehículo
DELETE {{baseUrl}}/vehiculos/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}